### ISSUE TITLE
[1.14.4] Mod conflict with Xearos

### ISSUE THREAD

**Issue by ProsperCraft** [rdvdev2/TimeTravelMod#51] opened 2019-07-22 12:08 UTC
TimeTravelMod-1.14.4-0.1.7.1

Crash report
https://gist.github.com/ProsperCraft/1f6cbc93776638cd731dc73cb888d6df

Logs-
[latest.log](https://github.com/rdvdev2/TimeTravelMod/files/3417239/latest.log)
[debug.log](https://github.com/rdvdev2/TimeTravelMod/files/3417240/debug.log)

Reproduced with only Xearos minimap and world map.
https://gist.github.com/ProsperCraft/d7d85f9eb938018c2fc9916b25d3ad02

**Comment by naritanara** [comment] 2019-07-22 12:41
By the crash log, seems like the problem is caused by Xearos code. Did you report the incompatibility to the Xearos developer?

**Comment by naritanara** [comment] 2019-07-22 13:05
Looking closer at Xearos code it looks fine. It may be a Forge bug. I will check it later.

**Comment by ProsperCraft** [comment] 2019-07-23 01:53
Still present in Forge .12 and TimeTravelMod-1.14.4-0.1.7.2.jar

https://gist.github.com/ProsperCraft/e89881940f2ea66062ef142eddb6b0bb

**Comment by naritanara** [comment] 2019-07-23 07:15
I investigated a little more and I was registering wrong my capability providers, I'm fixing it.

**Comment by naritanara** [comment] 2019-07-23 07:18
Fix will be included in 1.14.4-0.1.7.3

**Closed as completed** 2019-07-23 07:17 UTC
Labels: bug, Mod conflict
